### ISSUE TITLE
Warehouse initialization

### ISSUE THREAD

**Issue by mobley-trent** [xanderhieken/SparkDataWarehouse#1]
The code in the notebook does not interact with the warehouse at all. We only read from the csv files, but I did not get where we actually create or load a warehouse

**Comment by xanderhieken** [comment]
This is an old project for school, so I’m not sure if everything still works the way it originally did. The notebook was only supposed to take the CSV files and create snappy parquet files as the warehouse. Nothing in this code was meant to interact with the warehouse- that’s up to you to play around with
